from bs4 import BeautifulSoup
import cdflib
import datetime as dt 
from .misc_functions import (determine_datetime_type, getTime)
import numpy as np
import os 
import pandas as pd 
import requests
import sys 

def find_instances(list1, list2):
    """For each item in list1,
    return a list of offsets to its occurences in list2
    """
    idx2return = []
    for i in list1:
        idx =  [pos for pos,j in enumerate(list2) if i==j]
        idx2return.append(idx[0])
    return idx2return

def retrieve_ead_data(year,month,day,spacecraft,local_dir=None,username=None,password=None):
    if local_dir is None:
        cwd = os.getcwd()
        local_dir = f'{cwd}/data/TS{spacecraft}/EAD/{year}/{month}/'
        if os.path.exists(f'{cwd}/data/') is False:
            os.mkdir(f'{cwd}/data/')
        if os.path.exists(f'{cwd}/data/TS{spacecraft}/') is False:
            os.mkdir(f'{cwd}/data/TS{spacecraft}/')
        if os.path.exists(f'{cwd}/data/TS{spacecraft}/EAD/') is False:
            os.mkdir(f'{cwd}/data/TS{spacecraft}/EAD/')   
        if os.path.exists(f'{cwd}/data/TS{spacecraft}/EAD/{year}') is False:
            os.mkdir(f'{cwd}/data/TS{spacecraft}/EAD/{year}')
        if os.path.exists(f'{cwd}/data/TS{spacecraft}/EAD/{year}/{month}') is False:
            os.mkdir(f'{cwd}/data/TS{spacecraft}/EAD/{year}/{month}') 

    if username is not None:

        # ---------------- Check definitive first
        base_url = f'https://tracers-portal.physics.uiowa.edu/teams/flight/SOC/TS{spacecraft}/ead/def'
        date_url = f'{base_url}/'
    
        page = requests.get(date_url,auth=(username,password))
        data = page.text
        soup = BeautifulSoup(data,"html.parser")
        ds = f'{year}{month}{day}'
        all_strings = soup.find_all('a')
        idx = []
        for i in range(len(all_strings)):
            string_name = all_strings[i].get('href')
            if string_name is not None:
                if ds in string_name:
                    idx.append(i)
        if len(idx) > 0:
            day_file = all_strings[idx[-1]].get('href')
            sys.stdout.write('\nDownloading '+f'{day_file}'+'\n')
            file_url_path = date_url + '/' + day_file
            local_file_path = local_dir + '/' + day_file 
            r = requests.get(file_url_path,auth=(username,password))
            with open(local_file_path,'wb') as df:
                df.write(r.content)           
            
        else:
            ymd = f'{year}-{month}-{day}'
            print(f"No defintive EAD TS{spacecraft} files for {ymd}!")


            print("Checking predictive...")
            date_url = f'https://tracers-portal.physics.uiowa.edu/teams/flight/SOC/TS{spacecraft}/ead/predict/'
            page = requests.get(date_url,auth=(username,password))
            data = page.text
            soup = BeautifulSoup(data,"html.parser")
            ds = f'{year}{month}{day}'
            all_strings = soup.find_all('a')
            idx = []
            for i in range(len(all_strings)):
                string_name = all_strings[i].get('href')
                if string_name is not None:
                    if ds in string_name:
                        idx.append(i)
            if len(idx) > 0:
                day_file = all_strings[idx[-1]].get('href')
                sys.stdout.write('\nDownloading '+f'{day_file}'+'\n')
                file_url_path = date_url + '/' + day_file
                local_file_path = local_dir + '/' + day_file 
                r = requests.get(file_url_path,auth=(username,password))
                with open(local_file_path,'wb') as df:
                    df.write(r.content)    
            else:
                print(f"No predictive EAD TS{spacecraft} files for {ymd}!")
    


            
    else:
        #  ** 2026-04-15: currently, EAD files are only available on the team portal, not public facing! **
        print('No publicly available EAD files!')
    
    return None 

    
# ++++++++++++++++++++++++++++++++++++++++++++++++++++

class EADload(getTime):
    """
    This class loads and reads ephemeris and attitude information from EAD files generated by SOC.
    
    Required inputs
    -------------------
    t0 = start time of observation (string in datetime format. i.e., '2025-11-06/12:00:34')
    tf = end time of observation in same format as t0
    spacecraft = '1' or '2' for whichever TRACERS satellite you're aiming to look at.
    """
    
    def __init__(self,t0,tf,spacecraft):
        super().__init__(t0=t0,tf=tf,spacecraft=spacecraft)
        self.spacecraft=spacecraft
    def read_data(self,params=None,local_dir=None,quiet=None,username=None,password=None):
        """
        Optional inputs:
        params: list of named parameters to load from EAD file
        local_dir: local path to store / search for EAD files
        quiet: default False. if True, will suppress printing file name that is being loaded
        username & password: required inputs if you wish to pull from team portal
        ** 2026-04-15: currently, EAD files are only available on the team portal, not public facing! **
        """
        if quiet is None:
            quiet = False
        files2load = []
        for d in range(len(self.date_list)):
            ds = self.date_list[d]
            year = ds.split('/')[0]
            month = ds.split('/')[1]
            day = ds.split('/')[2]
            date_string = year+month+day
            cwd = os.getcwd()
            
            if local_dir is None:
                cwd = os.getcwd()
                local_dir = f'{cwd}/data/TS{self.spacecraft}/EAD/{year}/{month}/'
                if os.path.exists(f'{cwd}/data/') is False:
                    os.mkdir(f'{cwd}/data/')
                if os.path.exists(f'{cwd}/data/TS{self.spacecraft}/') is False:
                    os.mkdir(f'{cwd}/data/TS{self.spacecraft}/')
                if os.path.exists(f'{cwd}/data/TS{self.spacecraft}/EAD/') is False:
                    os.mkdir(f'{cwd}/data/TS{self.spacecraft}/EAD/')   
                if os.path.exists(f'{cwd}/data/TS{self.spacecraft}/EAD/{year}') is False:
                    os.mkdir(f'{cwd}/data/TS{self.spacecraft}/EAD/{year}')
                if os.path.exists(f'{cwd}/data/TS{self.spacecraft}/EAD/{year}/{month}') is False:
                    os.mkdir(f'{cwd}/data/TS{self.spacecraft}/EAD/{year}/{month}') 
                date_dir = f'{cwd}/data/TS{self.spacecraft}/EAD/{year}/{month}'

            else:
                date_dir = local_dir

            f2find = f'{date_dir}/ts{self.spacecraft}_def_ead**{date_string}**.cdf'
            out = os.popen(f'ls -rt {f2find}').read()
            ead_local_files = out.split('\n')[0:-1]
            
            if len(ead_local_files) > 0:
                files2load.append(ead_local_files[-1])
            else:
                ead_download = retrieve_ead_data(year,month,day,self.spacecraft, local_dir=local_dir, \
                                                 username=username, password=password)
                f2find = f'{date_dir}/ts{self.spacecraft}**_ead_**{date_string}**.cdf'
                out = os.popen(f'ls -rt {f2find}').read()
                ead_local_files = out.split('\n')[0:-1]
                if len(ead_local_files) > 0:
                    files2load.append(ead_local_files[-1])

        self.filenames = files2load
        if len(files2load) > 0:
            ead_dict = read_ead_files(files2load, start=self.start, end=self.end, params=params, quiet=quiet)
        else:
            ead_dict = {}
            print('No EAD files to load!')
        return ead_dict 

# ++++++++++++++++++++++++++++++++++++++++++++++++++++


def read_ead_files(files2load, start=None, end=None, params=None, quiet=None):
    """
    This function reads in EAD files. Required input is a list of file names.
    Optional input includes a start time (string), end time (string), and list of parameters to load.
    Default is loading the entire list of parameters. Valid parameter codes to request are as follows:
    
    'r_gei','v_gei','r_geo','lat_geo','lon_geo','r_geo','lat_geod','lon_geod','alt_geod','r_sm',
    'mlat','mlt','orbit','ltdn','b_gei','spin_lat','spin_lon','spin_phase'    
    """
    if quiet is None:
        quiet = False
        
    sc = (files2load[0].split('/')[-1]).split('_')[0]
    
    param_list = [f'{sc}_ead_r_gei2000',f'{sc}_ead_v_gei2000',f'{sc}_ead_r_geo',f'{sc}_ead_lat_geo',\
                   f'{sc}_ead_lon_geo',f'{sc}_ead_radius_geo',f'{sc}_ead_lat_geod',f'{sc}_ead_lon_geod',\
                   f'{sc}_ead_altitude_geod',f'{sc}_ead_r_sm',f'{sc}_ead_mlat',f'{sc}_ead_mlt',\
                   f'{sc}_ead_orbit_num',f'{sc}_ead_ltdn',f'{sc}_ead_b_gei2000',f'{sc}_ead_spin_axis_lat_gei2000',\
                   f'{sc}_ead_spin_axis_lon_gei2000',f'{sc}_ead_spin_phase1']
    param_codes = ['r_gei','v_gei','r_geo','lat_geo','lon_geo','r_geo','lat_geod','lon_geod','alt_geod','r_sm',\
                   'mlat','mlt','orbit','ltdn','b_gei','spin_lat','spin_lon','spin_phase']

    threeD_params = [f'{sc}_ead_b_gei2000',f'{sc}_ead_r_sm',f'{sc}_ead_r_geo',f'{sc}_ead_r_gei2000',f'{sc}_ead_v_gei2000']
                       
    if params is not None:
        overlap_idx = find_instances(params,param_codes)
        param_list = [param_list[x] for x in overlap_idx]
                    
    data_dict = {'dt':[],'utc':[]}
    for key in param_list:
        data_dict[key] = []
    param_shape = []                       
    for q in range(len(files2load)):
        file = files2load[q]
        cdf_file = cdflib.CDF(file)
        
        if quiet is False:
            print(file)            
        # Converting from nonsensical time to UTC.
        # These are the times at the midpoint of each energy sweep.
        dt_from_cdf = cdflib.cdfepoch.to_datetime(cdf_file['Epoch'])
        dts = pd.to_datetime(dt_from_cdf)
        utcs = [(x - pd.Timestamp('1970-01-01'))/pd.Timedelta('1s') for x in dts]

        data_dict['dt'].append(dts)
        data_dict['utc'].append(utcs)

        for j in range(len(param_list)):
            param2load = param_list[j]
            var_dat = cdf_file[param2load]
            data_dict[param2load].append(var_dat)
            if q == 0:
                param_shape.append(np.shape(var_dat))
    
    # ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    # RESHAPING ARRAYS BASED ON MULTIPLE FILES   
    n_files = len(files2load)
    t_tot = 0
    t_shapes = []
    for i in range(n_files):
        d2 = np.shape(data_dict['dt'][i])[0]
        t_tot = t_tot + int(d2)
        t_shapes.append(d2)

    reshape_dict = {'times':np.zeros(t_tot),'dt':np.zeros(t_tot)}
    for p in range(len(param_list)):
        if param_list[p] in threeD_params:
            reshape_dict[param_list[p]] = np.zeros((t_tot, 3))
        else:
            reshape_dict[param_list[p]] = np.zeros((t_tot))        

    
    for k in range(n_files):
        if k == 0:
            indices = [0,t_shapes[k]]
        elif k != 0 and k < n_files - 1:
            prior_indices = np.sum(t_shapes[0:k])
            indices = [prior_indices,prior_indices+t_shapes[k]]
        else:
            prior_indices = np.sum(t_shapes[0:k])
            indices = [prior_indices,t_tot]
        reshape_dict['times'][indices[0]:indices[1]] = data_dict['utc'][k]
        reshape_dict['dt'][indices[0]:indices[1]] = data_dict['dt'][k]

        for param in param_list:
            if param in threeD_params:
                reshape_dict[param][indices[0]:indices[1],:] = data_dict[param][k]
            else:
                reshape_dict[param][indices[0]:indices[1]] = data_dict[param][k]
            
    times = reshape_dict['times']
    nan_idx = list(np.where(np.isfinite(times) == False)[0])

    if len(nan_idx) > 0:
        for idx in nan_idx:
            if idx == 0 :
                ii = [idx+1, idx+2]
                time_res = abs(times[ii[1]] - times[ii[0]])
                new_time = times[ii[0]] - time_res
            elif idx != len(data_dict['utc']) - 1:
                ii = [idx-1,idx+2]
                new_time = (times[ii[0]] + times[ii[1]])/2.
            else:
                ii = [idx-2, idx-1]
                time_res = abs(times[ii[1]] - times[ii[0]])
                new_time = times[ii[1]] + time_res                
            times[idx] = new_time 

    if start is None and end is None:
        f_time = (files2load[0].split('v')[0]).split('_')[-2]
        start = dt.datetime.strptime(f_time,'%Y%m%d')

        f_time2 = (files2load[-1].split('v')[0]).split('_')[-2]
        s2 = dt.datetime.strptime(f_time2,'%Y%m%d')
        end = s2 + dt.timedelta(days=1)
    
    if isinstance(start,str):
        dt_fmt = determine_datetime_type(start)
        start = dt.datetime.strptime(start, dt_fmt)
        end = dt.datetime.strptime(end, dt_fmt)

    
    start_time = (start - dt.datetime(1970,1,1)).total_seconds()
    end_time = (end - dt.datetime(1970,1,1)).total_seconds()
    time_mask = (times >= start_time)&(times <= end_time) 


    out_dict = {'UTC':times[time_mask]}
    for param in param_list: 
        if param in threeD_params:
            out_dict[param] = reshape_dict[param][time_mask,:]
        else:
            out_dict[param] = reshape_dict[param][time_mask]

    out_dict['DT'] = []
    for elem in out_dict['UTC']:
        out_dict['DT'].append(dt.datetime.fromtimestamp(elem,dt.UTC))
 
    return out_dict




    
